### ISSUE TITLE
border-bottom cutting through text

### ISSUE THREAD

**Issue by robbybro** [AchillesPT/achilles-patient-interface#8]
Repro:
go to pushups
border-bottom of top 50% cuts through text
Expected: border goes beneath text
![image](https://cloud.githubusercontent.com/assets/3459667/7973914/2e98bbd6-0a10-11e5-8247-379df83316cf.png)

**Comment by puddi** [comment]
unable to replicate on my device. once you get here, show me and i'll take a better look

**Comment by puddi** [comment]
apparently this isn't a problem, just a problem w/ chrome :^)
